"""Initial migration

Revision ID: 33f3e15b8807
Revises: 
Create Date: 2026-04-29 14:54:33.172338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33f3e15b8807'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column('applications', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('applications', 'corpus',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    op.alter_column('applications', 'preferred_floor',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('applications_student_id_fkey'), 'applications', type_='foreignkey')
    op.alter_column('checkins', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('checkins', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('checkins', 'checkin_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('checkins', 'checkout_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(op.f('checkins_student_id_fkey'), 'checkins', type_='foreignkey')
    op.drop_constraint(op.f('checkins_room_id_fkey'), 'checkins', type_='foreignkey')
    op.alter_column('dormitories', 'name',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=2),
               existing_nullable=False)
    op.drop_constraint(op.f('dormitories_name_key'), 'dormitories', type_='unique')
    op.alter_column('rooms', 'qty_person',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('4'))
    op.alter_column('rooms', 'who',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    op.alter_column('rooms', 'corpus',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    op.alter_column('rooms', 'status',
               existing_type=sa.VARCHAR(length=1),
               nullable=False,
               existing_server_default=sa.text("'a'::character varying"))
    op.drop_constraint(op.f('rooms_number_corpus_key'), 'rooms', type_='unique')
    op.alter_column('students', 'gender',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    op.alter_column('students', 'course',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('students', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('students', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('students_email_key'), 'students', type_='unique')
    op.alter_column('users', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'student'::character varying"))
    op.alter_column('users', 'is_registered',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint(op.f('users_student_id_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_student_id_fkey'), 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('users_student_id_fkey'), 'users', 'students', ['student_id'], ['id_student'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_student_id_key'), 'users', ['student_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'is_registered',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'student'::character varying"))
    op.alter_column('users', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(op.f('students_email_key'), 'students', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('students', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('students', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('students', 'course',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('students', 'gender',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    op.create_unique_constraint(op.f('rooms_number_corpus_key'), 'rooms', ['number', 'corpus'], postgresql_nulls_not_distinct=False)
    op.alter_column('rooms', 'status',
               existing_type=sa.VARCHAR(length=1),
               nullable=True,
               existing_server_default=sa.text("'a'::character varying"))
    op.alter_column('rooms', 'corpus',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    op.alter_column('rooms', 'who',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    op.alter_column('rooms', 'qty_person',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('4'))
    op.create_unique_constraint(op.f('dormitories_name_key'), 'dormitories', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('dormitories', 'name',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.create_foreign_key(op.f('checkins_room_id_fkey'), 'checkins', 'rooms', ['room_id'], ['id_room'])
    op.create_foreign_key(op.f('checkins_student_id_fkey'), 'checkins', 'students', ['student_id'], ['id_student'])
    op.alter_column('checkins', 'checkout_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('checkins', 'checkin_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('checkins', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('checkins', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(op.f('applications_student_id_fkey'), 'applications', 'students', ['student_id'], ['id_student'])
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('applications', 'preferred_floor',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('applications', 'corpus',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    op.alter_column('applications', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
