"""initial

Revision ID: 89bd7c1b7231
Revises: 
Create Date: 2026-05-03 01:07:19.423777

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "89bd7c1b7231"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dormitories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "students",
        sa.Column("id_student", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("gender", sa.String(length=1), nullable=False),
        sa.Column("course", sa.Integer(), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id_student"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "applications",
        sa.Column("id_application", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("corpus", sa.String(length=1), nullable=False),
        sa.Column("preferred_floor", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="pending", nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["students.id_student"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id_application"),
    )
    op.create_table(
        "rooms",
        sa.Column("id_room", sa.Integer(), nullable=False),
        sa.Column("dormitory_id", sa.Integer(), nullable=False),
        sa.Column("floor", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("qty_person", sa.Integer(), server_default="4", nullable=False),
        sa.Column("who", sa.String(length=1), nullable=False),
        sa.Column("corpus", sa.String(length=1), nullable=False),
        sa.Column("status", sa.String(length=1), server_default="a", nullable=False),
        sa.ForeignKeyConstraint(
            ["dormitory_id"], ["dormitories.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id_room"),
        sa.UniqueConstraint("number", "corpus", name="uq_room_number_corpus"),
    )
    op.create_table(
        "users",
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role", sa.String(length=20), server_default="student", nullable=False
        ),
        sa.Column("is_registered", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"], ["students.id_student"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id_user"),
        sa.UniqueConstraint("student_id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "checkins",
        sa.Column("id_checkin", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column(
            "checkin_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("checkout_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id_room"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["student_id"], ["students.id_student"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id_checkin"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("checkins")
    op.drop_table("users")
    op.drop_table("rooms")
    op.drop_table("applications")
    op.drop_table("students")
    op.drop_table("dormitories")
    # ### end Alembic commands ###
